"""博物馆配置（配置驱动导入）。

新增"简单型"博物馆只需在此文件 MUSEUMS 列表里加一条 dict，无需写 .py。
特殊情况（xlsx 结构特殊、需要自定义逻辑）仍在 importers/ 下写 .py，会优先于配置。

=== 支持的 mode ===

simple          → simple_import_museum
                  xlsx 有名称列 + 图片保存位置列，rglob 自动查找图片
                  支持 name_col/dynasty_col/intro_col/category_col/size_col/path_col
                  strip_prefix=True 自动去除字段值前缀（如"年代：清"→"清"）

xlsx_name       → xlsx_name_import_museum
                  xlsx 有名称列（+介绍列），图片文件名 = 文物名

category_subdir → category_subdir_import_museum
                  无 xlsx，图片按类别分子目录，文件名 = 文物名

info_3d         → info_3d_import_museum
                  标准 info.xlsx 格式（序号|分类|定名|尺寸|年代|简介|存储类型|备注|资源文件路径）
                  资源文件路径以#分隔，只取图片部分，3D数据跳过

=== 单 xlsx vs 多 xlsx ===

单 xlsx：用 "xlsx" 字段
多 xlsx：用 "files" 列表，每项可含 xlsx/category_top + 字段覆盖
多 xlsx 时 product_id 自动带文件标识：某馆_书画_001

字段说明见各 mode 对应函数签名（__init__.py）。
"""

MUSEUMS = [
    # ============================================================
    # 已导入的博物馆（从 .py 迁移过来，共 9 个）
    # ============================================================

    # --- simple 模式 ---
    {
        "name": "苏州丝绸博物馆",
        "mode": "simple",
        "id_prefix": "苏州丝绸",
        "xlsx": "精品文物鉴赏_苏州丝绸博物馆.xlsx",
    },
    {
        "name": "聂荣臻元帅网 -- 馆藏文物",
        "mode": "simple",
        "id_prefix": "聂荣臻",
        "xlsx": "聂荣臻元帅网 -- 馆藏文物.xlsx",
    },
    {
        "name": "福州市林则徐纪念馆",
        "mode": "simple",
        "id_prefix": "林则徐",
        "xlsx": "福州市林则徐纪念馆.xlsx",
    },
    {
        "name": "金华市博物馆",
        "mode": "simple",
        "id_prefix": "金华",
        "xlsx": "金华市博物馆.xlsx",
    },

    # --- xlsx_name 模式 ---
    {
        "name": "仪征博物馆",
        "mode": "xlsx_name",
        "id_prefix": "仪征",
        "xlsx": "仪征博物馆.xlsx",
        "name_col": "文物名称",
        "intro_col": "介绍",
    },
    {
        "name": "莆田博物馆",
        "mode": "xlsx_name",
        "id_prefix": "莆田",
        "xlsx": "莆田博物馆.xlsx",
        "name_col": "文物名称",
        "intro_col": "介绍",
        "name_as_image_filename": True,
    },

    # --- category_subdir 模式 ---
    {
        "name": "李白纪念馆",
        "mode": "category_subdir",
        "id_prefix": "李白",
        "category_to_top": {
            "书画": "书画",
            "其他": "杂项",
            "古籍文献": "古籍文献",
            "碑刻": "石刻",
        },
    },
    {
        "name": "株洲博物馆",
        "mode": "category_subdir",
        "id_prefix": "株洲",
        "category_to_top": {
            "瓷器": "陶瓷器", "陶器": "陶瓷器",
            "铜器": "青铜器", "铁器": "青铜器",
            "玉器": "玉器", "金银器": "金银器",
            "石器": "石刻", "木": "漆器", "复合器": "杂项",
        },
    },
    {
        "name": "青白江博物馆",
        "mode": "category_subdir",
        "id_prefix": "青白江",
        "category_to_top": {
            "玉器": "玉器", "石器": "石刻",
            "青铜器": "青铜器", "瓷器": "陶瓷器", "陶器": "陶瓷器",
            "其他": "杂项",
        },
    },

    # ============================================================
    # 新增博物馆（94个）
    # ============================================================

    # --- 八爪鱼格式（标题列 + 图片_保存位置） ---
    {
        "name": "南通博物苑",
        "mode": "simple",
        "id_prefix": "南通",
        "xlsx": "南通博物苑.xlsx",
        "name_col": "定名",
        "dynasty_col": "年代_尺寸",
        "intro_col": "简介",
        "category_col": "类别",
    },
    {
        "name": "常州博物馆",
        "mode": "simple",
        "id_prefix": "常州",
        "xlsx": "常州博物馆.xlsx",
        "name_col": "定名",
        "intro_col": "描述",
    },
    {
        "name": "常熟博物馆",
        "mode": "simple",
        "id_prefix": "常熟",
        "xlsx": "常熟博物馆.xlsx",
        "name_col": "定名",
        "intro_col": "简述",
    },
    {
        "name": "景德镇中国陶瓷博物馆",
        "mode": "simple",
        "id_prefix": "景德镇陶瓷",
        "xlsx": "景德镇中国陶瓷博物馆.xlsx",
        "name_col": "定名",
        "intro_col": "简介",
    },
    {
        "name": "查询结果_徐州博物馆",
        "mode": "simple",
        "id_prefix": "徐州",
        "xlsx": "查询结果_徐州博物馆.xlsx",
        "name_col": "定名",
        "dynasty_col": "年代",
        "intro_col": "简介",
        "size_col": "尺寸",
    },
    {
        "name": "瑞金中央革命根据地纪念馆",
        "mode": "simple",
        "id_prefix": "瑞金",
        "xlsx": "瑞金中央革命根据地纪念馆.xlsx",
        "name_col": "定名",
        "intro_col": "简介",
        "category_col": "类别",
    },
    {
        "name": "苏州博物馆",
        "mode": "simple",
        "id_prefix": "苏州博物馆",
        "xlsx": "苏州博物馆.xlsx",
        "name_col": "定名",
        "category_col": "类别",
    },
    {
        "name": "界首博物馆",
        "mode": "simple",
        "id_prefix": "界首",
        "xlsx": "界首博物馆.xlsx",
        "name_col": "字段2",
        "intro_col": "正文",
        "path_col": "字段1_保存位置",
    },
    {
        "name": "西北农耕博物馆",
        "mode": "simple",
        "id_prefix": "西北农耕",
        "xlsx": "西北农耕博物馆.xlsx",
    },
    {
        "name": "西安事变纪念馆",
        "mode": "simple",
        "id_prefix": "西安事变",
        "xlsx": "西安事变纪念馆.xlsx",
        "intro_col": "文本",
    },
    {
        "name": "西安事变纪念馆陈列",
        "mode": "simple",
        "id_prefix": "西安事变陈列",
        "xlsx": "西安事变纪念馆陈列.xlsx",
    },
    {
        "name": "云南博物馆",  # 云南省博物馆
        "mode": "simple",
        "id_prefix": "云南",
        "xlsx": "云南省博物馆.xlsx",
        "name_col": "ellipsis",
        "dynasty_col": "年代",
        "intro_col": "介绍",
        "category_col": "标题",
    },
    {
        "name": "周恩来邓颖超纪念馆",
        "mode": "simple",
        "id_prefix": "周邓",
        "xlsx": "周恩来邓颖超纪念馆.xlsx",
        "dynasty_col": "文本1",
        "intro_col": "文本5",
    },
    {
        "name": "四川博物馆",  # 四川博物院
        "mode": "simple",
        "id_prefix": "四川",
        "xlsx": "四川博物院.xlsx",
        "dynasty_col": "年代",
        "intro_col": "简介",
        "size_col": "尺寸",
    },
    {
        "name": "温州博物馆",
        "mode": "simple",
        "id_prefix": "温州",
        "xlsx": "温州博物馆.xlsx",
        "name_col": "标题1",
        "dynasty_col": "年代",
        "intro_col": "内容",
        "category_col": "标题",
        "size_col": "尺寸",
        "path_col": "字段1_保存位置",
    },
    {
        "name": "西湖博物馆总馆",
        "mode": "simple",
        "id_prefix": "西湖",
        "xlsx": "西湖博物馆总馆.xlsx",
        "name_col": "名称",
        "size_col": "字段2",
    },
    {
        "name": "贵州博物馆",  # 贵州省博物馆
        "mode": "simple",
        "id_prefix": "贵州",
        "xlsx": "贵州省博物馆.xlsx",
        "intro_col": "textellipsis",
    },
    {
        "name": "郑州博物馆",
        "mode": "simple",
        "id_prefix": "郑州",
        "xlsx": "郑州博物馆.xlsx",
        "intro_col": "bd_con_c",
    },
    {
        "name": "深圳博物馆",
        "mode": "simple",
        "id_prefix": "深圳",
        "xlsx": "典藏-改革开放1.xlsx",
        "dynasty_col": "文本",
        "intro_col": "文本2",
        "size_col": "文本1",
    },
    {
        "name": "海南省博物馆",
        "mode": "simple",
        "id_prefix": "海南",
        "xlsx": "海南省博物馆.xlsx(1).xlsx",
        "name_col": "文本",
        "dynasty_col": "文本2",
        "category_col": "文本3",
        "size_col": "文本4",
        "strip_prefix": False,
    },
    {
        "name": "广东省博物馆",
        "mode": "simple",
        "id_prefix": "广东",
        "xlsx": "广东省博物馆0.xlsx",
        "name_col": "名称",
        "dynasty_col": "年代",
        "category_col": "类型",
        "size_col": "尺寸",
        "strip_prefix": False,
    },
    {
        "name": "广东省博物馆-1",
        "mode": "simple",
        "id_prefix": "广东1",
        "xlsx": "广东省博物馆.xlsx",
        "name_col": "名称",
        "dynasty_col": "年代",
        "category_col": "分类",
        "size_col": "尺寸",
        "strip_prefix": False,
    },
    {
        "name": "广州艺术博物院",
        "mode": "simple",
        "id_prefix": "广州艺术",
        "xlsx": "广州艺术博物院.xlsx",
        "intro_col": "文本",
    },
    {
        "name": "遵义会议纪念馆",
        "mode": "simple",
        "id_prefix": "遵义",
        "xlsx": "遵义会议纪念馆.xlsx",
        "dynasty_col": "年代",
        "intro_col": "文物名称",  # 可能是简介
        "size_col": "尺寸",
        "category_col": "质地",
        "strip_prefix": False,
    },
    {
        "name": "桂林博物馆-梅瓶",
        "mode": "simple",
        "id_prefix": "桂林梅瓶",
        "xlsx": "梅瓶-桂林博物馆.xlsx",
    },
    {
        "name": "桂林博物馆-书画",
        "mode": "simple",
        "id_prefix": "桂林书画",
        "xlsx": "书画-桂林博物馆.xlsx",
    },
    {
        "name": "桂林博物馆-杂项",
        "mode": "simple",
        "id_prefix": "桂林杂项",
        "xlsx": "杂项-桂林博物馆.xlsx",
        "name_col": "字段1",
    },
    {
        "name": "河南博物馆-青铜器",
        "mode": "simple",
        "id_prefix": "河南青铜",
        "xlsx": "青铜器.xlsx",
        "name_col": "标题",
        "category_col": "字段1",
        "dynasty_col": "文本",
        "intro_col": "文本2",
        "size_col": "文本1",
        "strip_prefix": False,
    },
    {
        "name": "广西民族博物馆",
        "mode": "simple",
        "id_prefix": "广西民族",
        "xlsx": "广西民族博物馆.xlsx",
        "dynasty_col": "时代",
        "size_col": "尺寸",
        "intro_col": "文物",
    },
    {
        "name": "海口博物馆",  # 海南省博物馆的另一个表
        "mode": "simple",
        "id_prefix": "海口",
        "xlsx": "海南省博物馆.xlsx(2).xlsx",
        "name_col": "文本",
        "dynasty_col": "文本2",
        "category_col": "文本3",
        "size_col": "文本4",
        "strip_prefix": False,
    },

    # --- 文化遗产格式（定名 + 资源文件路径，图片在 images/ 目录） ---
    {
        "name": "东北烈士纪念馆",
        "mode": "simple",
        "id_prefix": "东北烈士",
        "xlsx": "东北烈士纪念馆.xlsx",
        "name_col": "定名",
        "path_col": "资源文件路径",
    },
    {
        "name": "中国文字博物馆",
        "mode": "simple",
        "id_prefix": "文字",
        "xlsx": "中国文字博物馆.xlsx",
        "name_col": "定名",
        "dynasty_col": "年代",
        "category_col": "分类",
        "path_col": "资源文件路径",
    },
    {
        "name": "南阳汉画馆",
        "mode": "simple",
        "id_prefix": "南阳汉画",
        "xlsx": "南阳汉画馆.xlsx",
        "name_col": "定名",
        "dynasty_col": "年代",
        "intro_col": "简介",
        "size_col": "尺寸",
        "category_col": "分类",
        "path_col": "资源文件路径",
    },
    {
        "name": "开封博物馆",
        "mode": "simple",
        "id_prefix": "开封",
        "xlsx": "开封博物馆.xlsx",
        "name_col": "定名",
        "dynasty_col": "年代",
        "intro_col": "简介",
        "size_col": "尺寸",
        "category_col": "分类",
        "path_col": "资源文件路径",
    },
    {
        "name": "武汉博物馆",
        "mode": "simple",
        "id_prefix": "武汉",
        "xlsx": "武汉博物馆.xlsx",
        "name_col": "定名",
        "dynasty_col": "年代",
        "intro_col": "简介",
        "size_col": "尺寸",
        "category_col": "分类",
        "path_col": "资源文件路径",
    },
    {
        "name": "武汉市中山舰博物馆",
        "mode": "simple",
        "id_prefix": "中山舰",
        "xlsx": "武汉市中山舰博物馆.xlsx",
        "name_col": "定名",
        "dynasty_col": "年代",
        "intro_col": "简介",
        "category_col": "分类",
        "path_col": "资源文件路径",
    },
    {
        "name": "洛阳博物馆",
        "mode": "simple",
        "id_prefix": "洛阳",
        "xlsx": "洛阳博物馆.xlsx",
        "name_col": "定名",
        "dynasty_col": "年代",
        "intro_col": "简介",
        "size_col": "尺寸",
        "category_col": "分类",
        "path_col": "资源文件路径",
    },
    {
        "name": "湖北省博物馆",
        "mode": "simple",
        "id_prefix": "湖北",
        "xlsx": "湖北省博物馆.xlsx",
        "name_col": "定名",
        "intro_col": "简介",
        "category_col": "分类",
        "path_col": "资源文件路径",
    },
    {
        "name": "湖南省博物馆",
        "mode": "simple",
        "id_prefix": "湖南",
        "xlsx": "湖南省博物馆.xlsx",
        "name_col": "定名",
        "dynasty_col": "年代",
        "intro_col": "简介",
        "size_col": "尺寸",
        "category_col": "分类",
        "path_col": "资源文件路径",
    },
    {
        "name": "荆州博物馆",
        "mode": "simple",
        "id_prefix": "荆州",
        "xlsx": "荆州博物馆.xlsx",
        "name_col": "定名",
        "dynasty_col": "年代",
        "intro_col": "简介",
        "size_col": "尺寸",
        "category_col": "分类",
        "path_col": "资源文件路径",
    },
    {
        "name": "黑龙江省博物馆",
        "mode": "simple",
        "id_prefix": "黑龙江",
        "xlsx": "黑龙江省博物馆.xlsx",
        "name_col": "定名",
        "dynasty_col": "年代",
        "size_col": "尺寸",
        "category_col": "分类",
        "path_col": "资源文件路径",
    },
    {
        "name": "黑龙江省民族博物馆",
        "mode": "simple",
        "id_prefix": "黑龙江民族",
        "xlsx": "黑龙江省民族博物馆.xlsx",
        "name_col": "定名",
        "dynasty_col": "年代",
        "intro_col": "简介",
        "size_col": "尺寸",
        "category_col": "分类",
        "path_col": "资源文件路径",
    },
    {
        "name": "宜昌博物馆",
        "mode": "simple",
        "id_prefix": "宜昌",
        "xlsx": "宜昌博物馆.xlsx",
        "name_col": "定名",
        "path_col": "图片_保存位置",
    },

    # --- 山东系列格式（定名 + 图片_保存位置，图片在 二维/ 目录） ---
    {
        "name": "山东博物馆",
        "mode": "simple",
        "id_prefix": "山东",
        "xlsx": "山东博物馆.xlsx",
        "name_col": "定名",
        "intro_col": "简介",
        "size_col": "尺寸",
        "category_col": "分类",
    },
    {
        "name": "宁夏固原博物馆",
        "mode": "simple",
        "id_prefix": "宁夏固原",
        "xlsx": "宁夏固原博物馆.xlsx",
        "name_col": "定名",
        "dynasty_col": "朝代",
        "intro_col": "简介",
        "category_col": "分类",
    },
    {
        "name": "旅顺博物馆",
        "mode": "simple",
        "id_prefix": "旅顺",
        "xlsx": "旅顺博物馆.xlsx",
        "name_col": "定名",
        "dynasty_col": "朝代",
        "intro_col": "简介",
        "size_col": "尺寸",
        "category_col": "分类",
    },
    {
        "name": "沈阳故宫博物院",
        "mode": "simple",
        "id_prefix": "沈阳故宫",
        "xlsx": "沈阳故宫博物院.xlsx",
        "name_col": "定名",
        "dynasty_col": "朝代",
        "intro_col": "简介",
        "category_col": "分类",
        "path_col": "图片路径",
    },
    {
        "name": "济南数字博物馆",
        "mode": "simple",
        "id_prefix": "济南数字",
        "xlsx": "济南数字博物馆.xlsx",
        "name_col": "定名",
        "dynasty_col": "朝代",
        "category_col": "分类",
    },
    {
        "name": "济宁市博物馆",
        "mode": "simple",
        "id_prefix": "济宁",
        "xlsx": "济宁市博物馆.xlsx",
        "name_col": "定名",
        "dynasty_col": "朝代",
        "size_col": "尺寸",
        "category_col": "分类",
        "path_col": "二维_保存位置",
    },
    {
        "name": "淄博博物馆",
        "mode": "simple",
        "id_prefix": "淄博",
        "xlsx": "淄博博物馆.xlsx.xlsx",
        "name_col": "定名",
        "dynasty_col": "朝代",
        "category_col": "分类",
    },
    {
        "name": "滕州市博物馆",
        "mode": "simple",
        "id_prefix": "滕州",
        "xlsx": "滕州市博物馆.xlsx",
        "name_col": "定名",
        "dynasty_col": "朝代",
        "category_col": "分类",
    },
    {
        "name": "潍坊博物馆",
        "mode": "simple",
        "id_prefix": "潍坊",
        "xlsx": "潍坊博物馆.xlsx",
        "name_col": "定名",
        "dynasty_col": "朝代",
        "category_col": "分类",
    },
    {
        "name": "烟台博物馆",
        "mode": "simple",
        "id_prefix": "烟台",
        "xlsx": "烟台博物馆.xlsx",
        "name_col": "定名",
        "dynasty_col": "朝代",
        "intro_col": "简介",
        "size_col": "尺寸",
        "category_col": "分类",
    },
    {
        "name": "赤峰博物馆",
        "mode": "simple",
        "id_prefix": "赤峰",
        "xlsx": "赤峰博物馆.xlsx",
        "name_col": "定名",
        "dynasty_col": "朝代",
        "intro_col": "简介",
        "size_col": "尺寸",
        "category_col": "分类",
    },
    {
        "name": "鄂尔多斯博物馆",
        "mode": "simple",
        "id_prefix": "鄂尔多斯",
        "xlsx": "鄂尔多斯博物馆.xlsx",
        "name_col": "定名",
        "dynasty_col": "朝代",
        "category_col": "分类",
    },
    {
        "name": "青岛山炮台遗址展览馆",
        "mode": "simple",
        "id_prefix": "青岛山炮台",
        "xlsx": "青岛山炮台遗址展览馆.xlsx",
        "name_col": "定名",
        "path_col": "图片链接1_保存位置",
    },
    {
        "name": "青岛市博物馆",
        "mode": "simple",
        "id_prefix": "青岛",
        "xlsx": "青岛市博物馆.xlsx",
        "name_col": "定名",
        "dynasty_col": "年代",
        "intro_col": "简介",
        "size_col": "尺寸",
        "category_col": "分类",
    },
    {
        "name": "青州市博物馆",
        "mode": "simple",
        "id_prefix": "青州",
        "xlsx": "青州市博物馆.xlsx",
        "name_col": "定名",
        "intro_col": "简介",
        "size_col": "尺寸",
        "category_col": "分类",
        "path_col": "图片链接_保存位置",
    },
    {
        "name": "青海省博物馆",
        "mode": "simple",
        "id_prefix": "青海",
        "xlsx": "青海省博物馆2.xlsx",
        "name_col": "定名",
        "dynasty_col": "朝代",
        "category_col": "分类",
        "path_col": "图片链接_保存位置",
    },
    {
        "name": "齐文化博物馆",
        "mode": "simple",
        "id_prefix": "齐文化",
        "xlsx": "齐文化博物馆.xlsx",
        "name_col": "定名",
        "dynasty_col": "朝代",
        "intro_col": "简介",
        "size_col": "尺寸",
        "path_col": "图片链接_保存位置",
    },
    {
        "name": "临沂市博物馆",
        "mode": "simple",
        "id_prefix": "临沂",
        "xlsx": "临沂市博物馆.xlsx",
        "name_col": "定名",
        "dynasty_col": "朝代",
        "intro_col": "简介",
        "size_col": "尺寸",
        "category_col": "分类",
    },
    {
        "name": "内蒙古博物院",
        "mode": "simple",
        "id_prefix": "内蒙古",
        "xlsx": "内蒙古博物院.xlsx",
        "name_col": "定名",
        "intro_col": "简介",
    },
    {
        "name": "孔子博物馆",
        "mode": "simple",
        "id_prefix": "孔子",
        "xlsx": "孔子博物馆.xlsx",
        "name_col": "定名",
        "intro_col": "简介",
        "size_col": "尺寸",
        "category_col": "分类",
    },

    # --- info_3d 模式（标准 info.xlsx + resource 目录） ---
    {
        "name": "中国南海博物馆",
        "mode": "info_3d",
        "id_prefix": "南海",
        "xlsx": "info.xlsx",
    },
    {
        "name": "天水市博物馆（天水市伏羲文化博物馆）",
        "mode": "info_3d",
        "id_prefix": "天水",
        "xlsx": "info.xlsx",
    },
    {
        "name": "广东中国客家博物馆",
        "mode": "info_3d",
        "id_prefix": "客家",
        "xlsx": "info.xlsx",
    },
    {
        "name": "广东海上丝绸之路博物馆",
        "mode": "info_3d",
        "id_prefix": "广东海丝",
        "xlsx": "info.xlsx",
    },
    {
        "name": "广州博物馆",
        "mode": "simple",
        "id_prefix": "广州",
        "xlsx": "广州博物馆-专题鉴赏.xlsx",
    },
    {
        "name": "河北博物院",
        "mode": "simple",
        "id_prefix": "河北",
        "xlsx": "河北博物院.xlsx",
        "name_col": "藏品名称",
        "dynasty_col": "时代",
        "category_col": "文物类别",
        "path_col": "图片链接_保存位置",
    },
    {
        "name": "广州博物馆-3d",
        "mode": "info_3d",
        "id_prefix": "广州3d",
        "xlsx": "info.xlsx",
    },
    {
        "name": "广州艺术博物院-3d",
        "mode": "info_3d",
        "id_prefix": "广州艺术3d",
        "xlsx": "info.xlsx",
    },
    {
        "name": "广西民族博物馆-3d",
        "mode": "info_3d",
        "id_prefix": "广西民族3d",
        "xlsx": "info.xlsx",
    },
    {
        "name": "河北博物院-3d",
        "mode": "info_3d",
        "id_prefix": "河北3d",
        "xlsx": "info.xlsx",
    },
    {
        "name": "海南省博物馆-3d",
        "mode": "info_3d",
        "id_prefix": "海南3d",
        "xlsx": "info.xlsx",
    },
    {
        "name": "深圳博物馆-3d",
        "mode": "info_3d",
        "id_prefix": "深圳3d",
        "xlsx": "info.xlsx",
    },
    {
        "name": "贵州省博物馆-3d",
        "mode": "info_3d",
        "id_prefix": "贵州3d",
        "xlsx": "info.xlsx",
    },
    {
        "name": "遵义会议纪念馆-3d",
        "mode": "info_3d",
        "id_prefix": "遵义3d",
        "xlsx": "info.xlsx",
    },
    {
        "name": "郑州博物馆-3d",
        "mode": "info_3d",
        "id_prefix": "郑州3d",
        "xlsx": "info.xlsx",
    },
    {
        "name": "鸦片战争博物馆",
        "mode": "info_3d",
        "id_prefix": "鸦片战争",
        "xlsx": "info.xlsx",
    },
    {
        "name": "孙中山故居纪念馆",
        "mode": "simple",
        "id_prefix": "孙中山故居",
        "xlsx": "字画文献.xlsx",
    },
    {
        "name": "孙中山故居纪念馆-民俗",
        "mode": "simple",
        "id_prefix": "孙中山民俗",
        "xlsx": "民俗文物.xlsx",
    },
    {
        "name": "孙中山故居纪念馆-3d",
        "mode": "info_3d",
        "id_prefix": "孙中山3d",
        "xlsx": "info.xlsx",
    },
    {
        "name": "河南博物馆-3d",
        "mode": "info_3d",
        "id_prefix": "河南3d",
        "xlsx": "info.xlsx",
    },

    # --- 八爪鱼标题格式（标题 + 图片链接_保存位置，时间戳文件名） ---
    {
        "name": "中国港口博物馆",
        "mode": "simple",
        "id_prefix": "港口",
        "xlsx": "中国港口博物馆.xlsx",
        "name_col": "标题1",
        "dynasty_col": "年代1",
        "category_col": "类别1",
        "size_col": "尺寸1",
        "intro_col": "特征1",
        "path_col": "图片链接1_保存位置",
    },
    {
        "name": "中国茶叶博物馆",
        "mode": "simple",
        "id_prefix": "茶叶",
        "xlsx": "中国茶叶博物馆.xlsx",
        "intro_col": "文本",
    },
    {
        "name": "西藏博物馆",
        "mode": "simple",
        "id_prefix": "西藏",
        "xlsx": "西藏博物馆.xlsx",
        "intro_col": "简介",
    },
    {
        "name": "浙江省博物馆-古籍",
        "mode": "simple",
        "id_prefix": "浙江古籍",
        "xlsx": "浙江省博物馆-古籍图书.xlsx",
        "name_col": "标题",
        "dynasty_col": "版本年代",
        "intro_col": "版本类型",
        "path_col": "URL_保存位置",
    },
    {
        "name": "浙江省博物馆-3d",
        "mode": "simple",
        "id_prefix": "浙江3d",
        "xlsx": "浙江省博物馆-3D文物.xlsx",
        "name_col": "名称",
        "dynasty_col": "年代",
        "intro_col": "简介",
        "size_col": "尺寸",
        "path_col": "URL_保存位置",
    },
    {
        "name": "重庆中国三峡博物馆",
        "mode": "simple",
        "id_prefix": "重庆三峡",
        "xlsx": "重庆中国三峡博物馆(7w张图片名称是时间戳).xlsx",
        "name_col": "标题",
        "dynasty_col": "年代",
        "category_col": "文物类型",
        "size_col": "具体尺寸",
        "strip_prefix": False,
    },
    {
        "name": "中国人民革命军事博物馆",
        "mode": "simple",
        "id_prefix": "军事",
        "xlsx": "中国人民革命军事博物馆.xlsx",
        "name_col": "文本",
        "dynasty_col": "年代",
        "intro_col": "简介",
        "path_col": "图片链接_保存位置",
        "strip_prefix": False,
    },
    {
        "name": "中国国家博物馆",
        "mode": "simple",
        "id_prefix": "国博",
        "xlsx": "馆藏精品-中国国家博物馆.xlsx",
        "name_col": "名称",
        "dynasty_col": "时代",
        "intro_col": "简介",
        "category_col": "分类",
        "path_col": "图片链接_保存位置",
    },
    {
        "name": "北京自然博物馆",
        "mode": "simple",
        "id_prefix": "北京自然",
        "xlsx": "馆藏信息-北京自然博物馆.xlsx",
        "name_col": "名称",
        "category_col": "分类",
        "path_col": "图片链接_保存位置",
    },
    {
        "name": "安徽中国徽州文化博物馆",
        "mode": "simple",
        "id_prefix": "徽州",
        "xlsx": "安徽中国徽州文化博物馆-2维图片.xlsx",
        "name_col": "名称",
        "dynasty_col": "年代",
        "intro_col": "简介",
        "size_col": "尺寸",
        "category_col": "类别",
        "path_col": "图片链接_保存位置",
    },
    {
        "name": "安徽博物院",
        "mode": "simple",
        "id_prefix": "安徽",
        "xlsx": "安徽博物院-典藏精选.xlsx",
        "name_col": "名称",
        "dynasty_col": "年代",
        "intro_col": "简介1",
        "category_col": "类别",
        "path_col": "图片链接_保存位置",
    },
    {
        "name": "宿州市博物馆",
        "mode": "simple",
        "id_prefix": "宿州",
        "xlsx": "宿州市博物馆.xlsx",
        "name_col": "字段",
        "dynasty_col": "年代",
        "category_col": "分类",
        "path_col": "图片链接_保存位置",
    },
    {
        "name": "平凉市博物馆",
        "mode": "simple",
        "id_prefix": "平凉",
        "xlsx": "精品典藏 - 平凉市博物馆.xlsx",
        "name_col": "名称",
        "dynasty_col": "时期",
        "category_col": "类别",
        "path_col": "图片链接_保存位置",
    },
    {
        "name": "淮北市博物馆",
        "mode": "simple",
        "id_prefix": "淮北",
        "xlsx": "淮北市博物馆馆藏藏品清单.xlsx",
        "name_col": "名称",
        "dynasty_col": "年代",
        "category_col": "类型",
        "path_col": "图片链接_保存位置",
    },
    {
        "name": "清华大学艺术博物馆",
        "mode": "simple",
        "id_prefix": "清华艺术",
        "xlsx": "清华大学艺术博物馆.xlsx",
        "dynasty_col": "时期",
        "path_col": "图片链接_保存位置",
    },
    {
        "name": "甘肃省博物馆",
        "mode": "simple",
        "id_prefix": "甘肃",
        "xlsx": "精品赏析 - 文物典藏 - 甘肃省博物馆.xlsx",
        "name_col": "名称",
        "dynasty_col": "时间",
        "intro_col": "简介",
        "size_col": "尺寸",
        "path_col": "图片链接_保存位置",
    },
    {
        "name": "福建博物院",
        "mode": "simple",
        "id_prefix": "福建",
        "xlsx": "典藏精品_福建博物院.xlsx",
        "name_col": "名称",
        "dynasty_col": None,
        "intro_col": "简介",
        "category_col": "分类",
        "path_col": "图片链接_保存位置",
    },
    {
        "name": "蚌埠市博物馆",
        "mode": "simple",
        "id_prefix": "蚌埠",
        "xlsx": "馆藏精品-蚌埠市博物馆.xlsx",
        "name_col": "名称",
        "dynasty_col": "年代",
        "intro_col": "简介",
        "path_col": "图片链接_保存位置",
    },
    {
        "name": "伪满皇宫博物院",
        "mode": "simple",
        "id_prefix": "伪满皇宫",
        "xlsx": "藏品类目 - 伪满皇宫博物院 - 伪满皇宫前身是民国时期管理吉林、黑龙江两省盐务的吉黑榷运局官署。.xlsx",
        "name_col": "定名",
        "intro_col": "简介",
        "path_col": "图片_保存位置",
    },
    {
        "name": "南京市博物总馆",
        "mode": "simple",
        "id_prefix": "南京总馆",
        "xlsx": "藏品精粹-南京市博物总馆.xlsx",
        "name_col": "定名",
        "dynasty_col": "年代",
        "intro_col": "简介",
        "size_col": "尺寸",
        "category_col": "分类",
        "path_col": "图片_保存位置",
    },
    {
        "name": "吉林省博物院",
        "mode": "simple",
        "id_prefix": "吉林",
        "xlsx": "馆藏精品 - 吉林省博物院.xlsx",
        "name_col": "定名",
        "intro_col": "简介",
        "path_col": "图片链接_保存位置",
    },
    {
        "name": "扬州博物馆-漆器",
        "mode": "simple",
        "id_prefix": "扬州漆器",
        "xlsx": "扬州博物馆-漆器.xlsx",
        "name_col": "定名",
        "dynasty_col": "年代",
        "size_col": "尺寸",
        "category_col": "category_top",  # 用固定值
    },
    {
        "name": "扬州博物馆-玉器",
        "mode": "simple",
        "id_prefix": "扬州玉器",
        "xlsx": "扬州博物馆-玉器.xlsx",
        "name_col": "定名",
        "dynasty_col": "年代",
        "size_col": "尺寸",
    },
    {
        "name": "扬州博物馆-雕版",
        "mode": "simple",
        "id_prefix": "扬州雕版",
        "xlsx": "扬州博物馆-雕版.xlsx",
        "name_col": "定名",
        "dynasty_col": "年代",
        "size_col": "尺寸",
    },
    {
        "name": "扬州博物馆-石刻砖瓦",
        "mode": "simple",
        "id_prefix": "扬州石刻",
        "xlsx": "扬州博物馆-石刻砖瓦.xlsx",
        "name_col": "定名",
        "dynasty_col": "年代",
        "size_col": "尺寸",
    },
    {
        "name": "扬州博物馆",
        "mode": "simple",
        "id_prefix": "扬州",
        "xlsx": "扬州博物馆.xlsx",
        "name_col": "定名",
        "dynasty_col": "年代",
        "size_col": "尺寸",
    },
    {
        "name": "扬州博物馆-金属器",
        "mode": "simple",
        "id_prefix": "扬州金属",
        "xlsx": "扬州博物馆-金属器.xlsx",
        "name_col": "定名",
        "dynasty_col": "年代",
        "size_col": "尺寸",
    },
    {
        "name": "无锡博物院",
        "mode": "simple",
        "id_prefix": "无锡",
        "xlsx": "无锡博物院(1).xlsx",
        "name_col": "定名",
        "dynasty_col": "年代",
        "intro_col": "简介",
        "category_col": "类别",
    },
    {
        "name": "无锡博物院-2",
        "mode": "simple",
        "id_prefix": "无锡2",
        "xlsx": "无锡博物院(2).xlsx",
        "name_col": "定名",
        "dynasty_col": "年代",
        "intro_col": "简介",
        "category_col": "类别",
    },
    {
        "name": "博物江西",
        "mode": "simple",
        "id_prefix": "江西",
        "xlsx": "博物江西.xlsx",
        "name_col": "定名",
        "dynasty_col": "年代",
        "intro_col": "简介",
        "size_col": "尺寸",
        "category_col": "分类",
    },
    {
        "name": "广东民间工艺博物馆-青瓷",
        "mode": "simple",
        "id_prefix": "广东工艺青瓷",
        "xlsx": "广东民间工艺博物馆_青瓷.xlsx",
        "category_col": "nr",
        "strip_prefix": False,
    },
    {
        "name": "广东民间工艺博物馆-广彩",
        "mode": "simple",
        "id_prefix": "广东工艺广彩",
        "xlsx": "广东民间工艺博物馆_广彩.xlsx",
        "category_col": "nr",
        "strip_prefix": False,
    },
    {
        "name": "广东民间工艺博物馆-广绣",
        "mode": "simple",
        "id_prefix": "广东工艺广绣",
        "xlsx": "广东民间工艺博物馆_广绣.xlsx",
        "category_col": "nr",
        "strip_prefix": False,
    },
    {
        "name": "广东民间工艺博物馆-彩瓷",
        "mode": "simple",
        "id_prefix": "广东工艺彩瓷",
        "xlsx": "广东民间工艺博物馆_彩瓷.xlsx",
        "name_col": "标题1",
        "category_col": "nr",
        "path_col": "图片链接1_保存位置",
        "strip_prefix": False,
    },
    {
        "name": "广西壮族自治区博物馆-玉石器",
        "mode": "simple",
        "id_prefix": "广西玉器",
        "xlsx": "玉石器.xlsx",
        "dynasty_col": "时代",
        "size_col": "尺寸",
        "path_col": "图片链接_保存位置",
    },
    {
        "name": "广西壮族自治区博物馆-书画",
        "mode": "simple",
        "id_prefix": "广西书画",
        "xlsx": "书画.xlsx",
        "dynasty_col": "时代",
        "size_col": "尺寸",
        "path_col": "图片链接_保存位置",
    },
    {
        "name": "广西壮族自治区博物馆-陶瓷器",
        "mode": "simple",
        "id_prefix": "广西陶瓷",
        "xlsx": "陶瓷器.xlsx",
        "dynasty_col": "时代",
        "size_col": "尺寸",
        "path_col": "图片链接_保存位置",
    },
    {
        "name": "广西壮族自治区博物馆-金属器",
        "mode": "simple",
        "id_prefix": "广西金属",
        "xlsx": "金属器.xlsx",
        "dynasty_col": "年代",
        "size_col": "尺寸",
        "path_col": "图片链接_保存位置",
    },
    {
        "name": "广西壮族自治区博物馆-其他文物",
        "mode": "simple",
        "id_prefix": "广西其他",
        "xlsx": "其他文物.xlsx",
        "dynasty_col": "年代",
        "size_col": "尺寸",
        "path_col": "图片链接_保存位置",
    },
    {
        "name": "安徽省博物院-数字藏品",
        "mode": "simple",
        "id_prefix": "安徽数字",
        "xlsx": "安徽博物院-数字藏品.xlsx",
        "name_col": "名称",
        "strip_prefix": False,
    },
    # 注：安阳博物馆由 anyang.py 手写导入器处理（有 3D 数据特殊逻辑），不在此配置

    # ============================================================
    # 故宫博物院（多 xlsx 分批，每个 xlsx 对应不同图片子目录）
    # ============================================================
    {
        "name": "故宫博物院-数字文物库",
        "mode": "simple",
        "id_prefix": "故宫",
        "name_col": "名称",
        "dynasty_col": "年代",
        "category_col": "分类",
        "path_col": "图片链接_保存位置",
        "files": [
            {"xlsx": "故宫博物院数字文物库-1-324.xlsx"},
            {"xlsx": "故宫博物院数字文物库-325-949.xlsx"},
            {"xlsx": "故宫博物院数字文物库-950-1399.xlsx"},
            {"xlsx": "故宫博物院数字文物库-1400-1999.xlsx"},
            {"xlsx": "故宫博物院数字文物库-2000-2594.xlsx"},
        ],
    },
    {
        "name": "故宫博物院-藏品",
        "mode": "simple",
        "id_prefix": "故宫藏品",
        "xlsx": "藏品 - 故宫博物院.xlsx",
        "name_col": "文物名称",
        "dynasty_col": "时代",
        "intro_col": "简介",
        "category_col": "分类",
        "path_col": "图片链接_保存位置",
    },
]
